[package]
name = "my-tunet"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
hmac = "0.12.1"
md-5 = "0.10.6"
regex = "1.11.1"
reqwest = "0.12.15"
sha-1 = "0.10.1"
tokio = { version = "1.45.0", features = ["macros", "rt-multi-thread"] }
